server:
  port: 8010
  # tomcat设置
  tomcat:
    # 开启日志访问
    max-threads: 1000
    min-spare-threads: 500
    uri-encoding: UTF-8
    basedir: ./
spring:
  http:
    encoding:
      force: true
      charset: UTF-8
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://119.23.32.199:3306/etutor?useUnicode=true&characterEncoding=UTF-8
    username: dbuser
    password: boom123321
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    #配置单机版 Redis
    host: localhost
    port: 6379
    password:

    #配置高可用集群
    sentinel:
      master: mymaster
      nodes: sentinelOS1:26379,sentinelOS2:26379,sentinelOS3:26379

  cache:
    type: redis #指定缓存类型
    cache-names: realTimeCache #指定缓存命名空间