server:
  port: 8010
    # tomcat设置
  tomcat:
    # 开启日志访问
    max-threads: 1000
    min-spare-threads: 500
    uri-encoding: UTF-8
    basedir: ./
spring:
  http:
    encoding:
      force: true
      charset: UTF-8
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://119.23.32.199:3306/etutor?useUnicode=true&characterEncoding=UTF-8
    username: dbuser
    password: boom123321
    type: com.alibaba.druid.pool.DruidDataSource